# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delivery.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditForm(object):
    def setupUi(self, lineEdit_name_2):
        lineEdit_name_2.setObjectName("lineEdit_name_2")
        lineEdit_name_2.resize(952, 826)
        lineEdit_name_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(lineEdit_name_2)
        self.centralwidget.setObjectName("centralwidget")
        self.labelProduct1 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct1.setGeometry(QtCore.QRect(40, 470, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelProduct1.sizePolicy().hasHeightForWidth()
        )
        self.labelProduct1.setSizePolicy(sizePolicy)
        self.labelProduct1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelProduct1.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProduct1.setTextFormat(QtCore.Qt.AutoText)
        self.labelProduct1.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelProduct1.setWordWrap(False)
        self.labelProduct1.setObjectName("labelProduct1")
        self.labelProduct2 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct2.setGeometry(QtCore.QRect(510, 470, 381, 31))
        self.labelProduct2.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct2.setObjectName("labelProduct2")
        self.labelProduct3 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct3.setGeometry(QtCore.QRect(510, 120, 401, 31))
        self.labelProduct3.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct3.setObjectName("labelProduct3")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(40, 60, 421, 41))
        self.lineEdit_name.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_name.setText("")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_price = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_price.setGeometry(QtCore.QRect(500, 60, 421, 41))
        self.lineEdit_price.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_price.setText("")
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.lineEdit_startDate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_startDate.setGeometry(QtCore.QRect(40, 160, 421, 41))
        self.lineEdit_startDate.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_startDate.setObjectName("lineEdit_startDate")
        self.calendarWidget_1 = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget_1.setGeometry(QtCore.QRect(50, 210, 401, 241))
        self.calendarWidget_1.setStyleSheet(
            "background-color: rgb(67, 202, 202);\n"
            'font: 75 9pt "MS Shell Dlg 2";\n'
            "border-radius: 10;\n"
            "color: rgb(0, 0, 0);"
        )
        self.calendarWidget_1.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget_1.setObjectName("calendarWidget_1")
        self.lineEdit_deliveryDate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_deliveryDate.setGeometry(QtCore.QRect(500, 160, 421, 41))
        self.lineEdit_deliveryDate.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_deliveryDate.setObjectName("lineEdit_deliveryDate")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget_2.setGeometry(QtCore.QRect(510, 210, 401, 241))
        self.calendarWidget_2.setStyleSheet(
            "background-color: rgb(67, 202, 202);\n"
            'font: 75 9pt "MS Shell Dlg 2";\n'
            "border-radius: 10;\n"
            "color: rgb(0, 0, 0);"
        )
        self.calendarWidget_2.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.lineEdit_product = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_product.setGeometry(QtCore.QRect(30, 510, 421, 41))
        self.lineEdit_product.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_product.setText("")
        self.lineEdit_product.setObjectName("lineEdit_product")
        self.comboBox_venicle = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_venicle.setGeometry(QtCore.QRect(500, 510, 421, 41))
        self.comboBox_venicle.setStyleSheet(
            "QComboBox{    \n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}\n"
            "QComboBox::drop-down {\n"
            "    background-color: rgb(255, 255, 255);\n"
            "    border-radius: 8;\n"
            "    width: 30;\n"
            "}\n"
            "QComboBox::down-arrow {\n"
            "    width: 0px;\n"
            "    height: 0px;\n"
            "    border-left: 5px solid transparent;\n"
            "    border-right: 5px solid transparent;\n"
            "    border-top: 5px solid black; /* Цвет стрелки */\n"
            "}\n"
            "QComboBox QAbstractItemView {\n"
            "    margin-top: 2;\n"
            "    color: rgb(255, 255, 255);\n"
            "    background-color: #373e4e;\n"
            "    padding: 10;\n"
            "    selection-background-color: rgb(39, 44, 54);\n"
            "}"
        )
        self.comboBox_venicle.setObjectName("comboBox_venicle")
        self.comboBox_supplier = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_supplier.setGeometry(QtCore.QRect(30, 610, 421, 41))
        self.comboBox_supplier.setStyleSheet(
            "QComboBox{    \n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}\n"
            "QComboBox::drop-down {\n"
            "    background-color: rgb(255, 255, 255);\n"
            "    border-radius: 8;\n"
            "    width: 30;\n"
            "}\n"
            "QComboBox::down-arrow {\n"
            "    width: 0px;\n"
            "    height: 0px;\n"
            "    border-left: 5px solid transparent;\n"
            "    border-right: 5px solid transparent;\n"
            "    border-top: 5px solid black; /* Цвет стрелки */\n"
            "}\n"
            "QComboBox QAbstractItemView {\n"
            "    margin-top: 2;\n"
            "    color: rgb(255, 255, 255);\n"
            "    background-color: #373e4e;\n"
            "    padding: 10;\n"
            "    selection-background-color: rgb(39, 44, 54);\n"
            "}"
        )
        self.comboBox_supplier.setObjectName("comboBox_supplier")
        self.lineEdit_quantity = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_quantity.setGeometry(QtCore.QRect(500, 610, 421, 41))
        self.lineEdit_quantity.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_quantity.setText("")
        self.lineEdit_quantity.setObjectName("lineEdit_quantity")
        self.OkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OkBtn.setGeometry(QtCore.QRect(40, 720, 211, 91))
        self.OkBtn.setStyleSheet(
            "QPushButton {\n"
            "     border-radius: 10px;\n"
            "     background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            '    font: 75 14pt "MS Shell Dlg 2";\n'
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.OkBtn.setCheckable(False)
        self.OkBtn.setChecked(False)
        self.OkBtn.setObjectName("OkBtn")
        self.CancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CancelBtn.setGeometry(QtCore.QRect(700, 720, 211, 91))
        self.CancelBtn.setStyleSheet(
            " QPushButton {\n"
            "     border-radius: 10px;\n"
            "     background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            '    font: 75 14pt "MS Shell Dlg 2";\n'
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.CancelBtn.setObjectName("CancelBtn")
        
        self.labelProduct1_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct1_3.setGeometry(QtCore.QRect(510, 20, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelProduct1_3.sizePolicy().hasHeightForWidth()
        )
        self.labelProduct1_3.setSizePolicy(sizePolicy)
        self.labelProduct1_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelProduct1_3.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct1_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProduct1_3.setTextFormat(QtCore.Qt.AutoText)
        self.labelProduct1_3.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelProduct1_3.setWordWrap(False)
        self.labelProduct1_3.setObjectName("labelProduct1_3")
        self.labelProduct1_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct1_4.setGeometry(QtCore.QRect(510, 565, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelProduct1_4.sizePolicy().hasHeightForWidth()
        )
        self.labelProduct1_4.setSizePolicy(sizePolicy)
        self.labelProduct1_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelProduct1_4.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct1_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProduct1_4.setTextFormat(QtCore.Qt.AutoText)
        self.labelProduct1_4.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelProduct1_4.setWordWrap(False)
        self.labelProduct1_4.setObjectName("labelProduct1_4")
        
        self.labelProduct2_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct2_3.setGeometry(QtCore.QRect(40, 570, 381, 31))
        self.labelProduct2_3.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct2_3.setObjectName("labelProduct2_3")
        
        
        self.labelProduct1_5 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct1_5.setGeometry(QtCore.QRect(50, 20, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelProduct1_5.sizePolicy().hasHeightForWidth()
        )
        self.labelProduct1_5.setSizePolicy(sizePolicy)
        self.labelProduct1_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelProduct1_5.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct1_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProduct1_5.setTextFormat(QtCore.Qt.AutoText)
        self.labelProduct1_5.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelProduct1_5.setWordWrap(False)
        self.labelProduct1_5.setObjectName("labelProduct1_5")
        self.lineEdit_startDate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_startDate.setGeometry(QtCore.QRect(40, 160, 421, 41))
        self.lineEdit_startDate.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_startDate.setObjectName("lineEdit_startDate")
        self.labelProduct3_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct3_2.setGeometry(QtCore.QRect(50, 120, 401, 31))
        self.labelProduct3_2.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct3_2.setObjectName("labelProduct3_2")
        
        lineEdit_name_2.setCentralWidget(self.centralwidget)

        self.retranslateUi(lineEdit_name_2)
        QtCore.QMetaObject.connectSlotsByName(lineEdit_name_2)

    def retranslateUi(self, lineEdit_name_2):
        _translate = QtCore.QCoreApplication.translate
        lineEdit_name_2.setWindowTitle(_translate("lineEdit_name_2", "Добавить поставку"))
        self.labelProduct1.setText(_translate("lineEdit_name_2", "Товар"))
        self.labelProduct2.setText(
            _translate("lineEdit_name_2", "Транспортное средство")
        )
        self.labelProduct3.setText(_translate("lineEdit_name_2", "Дата поставки"))
        self.OkBtn.setText(_translate("lineEdit_name_2", "OK"))
        self.CancelBtn.setText(_translate("lineEdit_name_2", "Отмена"))
        self.labelProduct1_3.setText(_translate("lineEdit_name_2", "Цена за 1 тонну"))
        self.labelProduct1_4.setText(_translate("lineEdit_name_2", "Количество тонн"))
        self.labelProduct2_3.setText(_translate("lineEdit_name_2", "Поставщик"))
        self.labelProduct1_5.setText(_translate("lineEdit_name_2", "Номер поставки"))
        self.labelProduct3_2.setText(_translate("lineEdit_name_2", "Дата заказа"))
