# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1340, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setMinimumSize(QtCore.QSize(0, 600))
        self.tabWidget_main.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            'font: 75 14pt "MS Shell Dlg 2";\n'
            'font: 12pt "MS Shell Dlg 2";'
        )
        self.tabWidget_main.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_main.setDocumentMode(True)
        self.tabWidget_main.setTabsClosable(False)
        self.tabWidget_main.setMovable(False)
        self.tabWidget_main.setTabBarAutoHide(False)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.products = QtWidgets.QWidget()
        self.products.setObjectName("products")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.products)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_Product = QtWidgets.QTableWidget(self.products)
        self.tableWidget_Product.setObjectName("tableWidget_Product")
        self.tableWidget_Product.setColumnCount(0)
        self.tableWidget_Product.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_Product)
        self.horizontalLayout_product = QtWidgets.QHBoxLayout()
        self.horizontalLayout_product.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_product.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_product.setSpacing(10)
        self.horizontalLayout_product.setObjectName("horizontalLayout_product")
        self.btn_edit_product = QtWidgets.QPushButton(self.products)
        self.btn_edit_product.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_product.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_product.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_edit_product.setObjectName("btn_edit_product")
        self.horizontalLayout_product.addWidget(self.btn_edit_product)
        self.btn_delete_product = QtWidgets.QPushButton(self.products)
        self.btn_delete_product.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_product.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_product.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_product.setObjectName("btn_delete_product")
        self.horizontalLayout_product.addWidget(self.btn_delete_product)
        self.lineEdit_search_product = QtWidgets.QLineEdit(self.products)
        self.lineEdit_search_product.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_search_product.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_search_product.setStyleSheet(
            "border: 3 solid rgb(0, 0, 0);\n"
            "border-radius: 10;\n"
            'font: 75 10pt "MS Shell Dlg 2";'
        )
        self.lineEdit_search_product.setText("")
        self.lineEdit_search_product.setObjectName("lineEdit_search_product")
        self.horizontalLayout_product.addWidget(self.lineEdit_search_product)
        self.search_btn_product = QtWidgets.QPushButton(self.products)
        self.search_btn_product.setMinimumSize(QtCore.QSize(0, 75))
        self.search_btn_product.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_btn_product.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}"
        )
        self.search_btn_product.setObjectName("search_btn_product")
        self.horizontalLayout_product.addWidget(self.search_btn_product)
        self.verticalLayout_4.addLayout(self.horizontalLayout_product)
        self.tabWidget_main.addTab(self.products, "")
        self.orders = QtWidgets.QWidget()
        self.orders.setObjectName("orders")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.orders)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_orders = QtWidgets.QTableWidget(self.orders)
        self.tableWidget_orders.setObjectName("tableWidget_orders")
        self.tableWidget_orders.setColumnCount(0)
        self.tableWidget_orders.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_orders)
        self.horizontalLayout_order = QtWidgets.QHBoxLayout()
        self.horizontalLayout_order.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_order.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_order.setSpacing(10)
        self.horizontalLayout_order.setObjectName("horizontalLayout_order")
        self.btn_add_orders = QtWidgets.QPushButton(self.orders)
        self.btn_add_orders.setMinimumSize(QtCore.QSize(200, 75))
        self.btn_add_orders.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_orders.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_add_orders.setObjectName("btn_add_orders")
        self.horizontalLayout_order.addWidget(self.btn_add_orders)
        self.btn_edit_order = QtWidgets.QPushButton(self.orders)
        self.btn_edit_order.setMinimumSize(QtCore.QSize(170, 75))
        self.btn_edit_order.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_order.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_edit_order.setObjectName("btn_edit_order")
        self.horizontalLayout_order.addWidget(self.btn_edit_order)
        self.btn_delete_order = QtWidgets.QPushButton(self.orders)
        self.btn_delete_order.setMinimumSize(QtCore.QSize(210, 75))
        self.btn_delete_order.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_order.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_order.setObjectName("btn_delete_order")
        self.horizontalLayout_order.addWidget(self.btn_delete_order)
        self.btn_delete_order_2 = QtWidgets.QPushButton(self.orders)
        self.btn_delete_order_2.setMinimumSize(QtCore.QSize(210, 75))
        self.btn_delete_order_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_order_2.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_order_2.setObjectName("btn_delete_order_2")
        self.horizontalLayout_order.addWidget(self.btn_delete_order_2)
        self.lineEdit_search_order = QtWidgets.QLineEdit(self.orders)
        self.lineEdit_search_order.setMinimumSize(QtCore.QSize(150, 40))
        self.lineEdit_search_order.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_search_order.setStyleSheet(
            "border: 3 solid rgb(0, 0, 0);\n"
            "border-radius: 10;\n"
            'font: 75 10pt "MS Shell Dlg 2";'
        )
        self.lineEdit_search_order.setObjectName("lineEdit_search_order")
        self.horizontalLayout_order.addWidget(self.lineEdit_search_order)
        self.search_btn_order = QtWidgets.QPushButton(self.orders)
        self.search_btn_order.setMinimumSize(QtCore.QSize(100, 75))
        self.search_btn_order.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_btn_order.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}"
        )
        self.search_btn_order.setObjectName("search_btn_order")
        self.horizontalLayout_order.addWidget(self.search_btn_order)
        self.btn_otchet_order = QtWidgets.QPushButton(self.orders)
        self.btn_otchet_order.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_otchet_order.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_otchet_order.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_otchet_order.setObjectName("btn_otchet_order")
        self.horizontalLayout_order.addWidget(self.btn_otchet_order)
        self.verticalLayout_5.addLayout(self.horizontalLayout_order)
        self.tabWidget_main.addTab(self.orders, "")
        self.Clients = QtWidgets.QWidget()
        self.Clients.setObjectName("Clients")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Clients)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_Clients = QtWidgets.QTableWidget(self.Clients)
        self.tableWidget_Clients.setObjectName("tableWidget_Clients")
        self.tableWidget_Clients.setColumnCount(0)
        self.tableWidget_Clients.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_Clients)
        self.horizontalLayout_order_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_order_2.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_order_2.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_order_2.setSpacing(10)
        self.horizontalLayout_order_2.setObjectName("horizontalLayout_order_2")
        self.btn_add_Clients = QtWidgets.QPushButton(self.Clients)
        self.btn_add_Clients.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_Clients.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_Clients.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_add_Clients.setObjectName("btn_add_Clients")
        self.horizontalLayout_order_2.addWidget(self.btn_add_Clients)
        self.btn_edit_Clients = QtWidgets.QPushButton(self.Clients)
        self.btn_edit_Clients.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_Clients.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_Clients.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_edit_Clients.setObjectName("btn_edit_Clients")
        self.horizontalLayout_order_2.addWidget(self.btn_edit_Clients)
        self.btn_delete_Clients = QtWidgets.QPushButton(self.Clients)
        self.btn_delete_Clients.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_Clients.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_Clients.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_Clients.setObjectName("btn_delete_Clients")
        self.horizontalLayout_order_2.addWidget(self.btn_delete_Clients)
        self.lineEdit_search_clients = QtWidgets.QLineEdit(self.Clients)
        self.lineEdit_search_clients.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_search_clients.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_search_clients.setStyleSheet(
            "border: 3 solid rgb(0, 0, 0);\n"
            "border-radius: 10;\n"
            'font: 75 10pt "MS Shell Dlg 2";'
        )
        self.lineEdit_search_clients.setObjectName("lineEdit_search_clients")
        self.horizontalLayout_order_2.addWidget(self.lineEdit_search_clients)
        self.search_btn_clients = QtWidgets.QPushButton(self.Clients)
        self.search_btn_clients.setMinimumSize(QtCore.QSize(0, 75))
        self.search_btn_clients.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_btn_clients.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}"
        )
        self.search_btn_clients.setObjectName("search_btn_clients")
        self.horizontalLayout_order_2.addWidget(self.search_btn_clients)
        self.verticalLayout_3.addLayout(self.horizontalLayout_order_2)
        self.tabWidget_main.addTab(self.Clients, "")
        self.suppliers = QtWidgets.QWidget()
        self.suppliers.setObjectName("suppliers")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.suppliers)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget_suppliers = QtWidgets.QTableWidget(self.suppliers)
        self.tableWidget_suppliers.setObjectName("tableWidget_suppliers")
        self.tableWidget_suppliers.setColumnCount(0)
        self.tableWidget_suppliers.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget_suppliers)
        self.horizontalLayout_suppliers = QtWidgets.QHBoxLayout()
        self.horizontalLayout_suppliers.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_suppliers.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_suppliers.setSpacing(10)
        self.horizontalLayout_suppliers.setObjectName("horizontalLayout_suppliers")
        self.btn_add_suppliers = QtWidgets.QPushButton(self.suppliers)
        self.btn_add_suppliers.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_suppliers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_suppliers.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_add_suppliers.setObjectName("btn_add_suppliers")
        self.horizontalLayout_suppliers.addWidget(self.btn_add_suppliers)
        self.btn_edit_suppliers = QtWidgets.QPushButton(self.suppliers)
        self.btn_edit_suppliers.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_suppliers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_suppliers.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_edit_suppliers.setObjectName("btn_edit_suppliers")
        self.horizontalLayout_suppliers.addWidget(self.btn_edit_suppliers)
        self.btn_delete_suppliers = QtWidgets.QPushButton(self.suppliers)
        self.btn_delete_suppliers.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_suppliers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_suppliers.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_suppliers.setObjectName("btn_delete_suppliers")
        self.horizontalLayout_suppliers.addWidget(self.btn_delete_suppliers)
        self.lineEdit_search_suppliers = QtWidgets.QLineEdit(self.suppliers)
        self.lineEdit_search_suppliers.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_search_suppliers.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_search_suppliers.setStyleSheet(
            "border: 3 solid rgb(0, 0, 0);\n"
            "border-radius: 10;\n"
            'font: 75 10pt "MS Shell Dlg 2";'
        )
        self.lineEdit_search_suppliers.setObjectName("lineEdit_search_suppliers")
        self.horizontalLayout_suppliers.addWidget(self.lineEdit_search_suppliers)
        self.search_btn_suppliers = QtWidgets.QPushButton(self.suppliers)
        self.search_btn_suppliers.setMinimumSize(QtCore.QSize(0, 75))
        self.search_btn_suppliers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_btn_suppliers.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}"
        )
        self.search_btn_suppliers.setObjectName("search_btn_suppliers")
        self.horizontalLayout_suppliers.addWidget(self.search_btn_suppliers)
        self.verticalLayout_6.addLayout(self.horizontalLayout_suppliers)
        self.tabWidget_main.addTab(self.suppliers, "")
        self.Delivery = QtWidgets.QWidget()
        self.Delivery.setObjectName("Delivery")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Delivery)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_Delivery = QtWidgets.QTableWidget(self.Delivery)
        self.tableWidget_Delivery.setObjectName("tableWidget_Delivery")
        self.tableWidget_Delivery.setColumnCount(0)
        self.tableWidget_Delivery.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_Delivery)
        self.horizontalLayout_Delivery = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Delivery.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_Delivery.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_Delivery.setSpacing(10)
        self.horizontalLayout_Delivery.setObjectName("horizontalLayout_Delivery")
        self.btn_add_Delivery = QtWidgets.QPushButton(self.Delivery)
        self.btn_add_Delivery.setMinimumSize(QtCore.QSize(200, 75))
        self.btn_add_Delivery.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_Delivery.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_add_Delivery.setObjectName("btn_add_Delivery")
        self.horizontalLayout_Delivery.addWidget(self.btn_add_Delivery)
        self.btn_edit_Delivery = QtWidgets.QPushButton(self.Delivery)
        self.btn_edit_Delivery.setMinimumSize(QtCore.QSize(170, 75))
        self.btn_edit_Delivery.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_Delivery.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_edit_Delivery.setObjectName("btn_edit_Delivery")
        self.horizontalLayout_Delivery.addWidget(self.btn_edit_Delivery)
        self.btn_delete_Delivery = QtWidgets.QPushButton(self.Delivery)
        self.btn_delete_Delivery.setMinimumSize(QtCore.QSize(210, 75))
        self.btn_delete_Delivery.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_Delivery.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_Delivery.setObjectName("btn_delete_Delivery")
        self.horizontalLayout_Delivery.addWidget(self.btn_delete_Delivery)
        self.btn_delete_Delivery_2 = QtWidgets.QPushButton(self.Delivery)
        self.btn_delete_Delivery_2.setMinimumSize(QtCore.QSize(210, 75))
        self.btn_delete_Delivery_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_Delivery_2.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_Delivery_2.setObjectName("btn_delete_Delivery_2")
        self.horizontalLayout_Delivery.addWidget(self.btn_delete_Delivery_2)
        self.lineEdit_search_delivery = QtWidgets.QLineEdit(self.Delivery)
        self.lineEdit_search_delivery.setMinimumSize(QtCore.QSize(150, 40))
        self.lineEdit_search_delivery.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_search_delivery.setStyleSheet(
            "border: 3 solid rgb(0, 0, 0);\n"
            "border-radius: 10;\n"
            'font: 75 10pt "MS Shell Dlg 2";'
        )
        self.lineEdit_search_delivery.setObjectName("lineEdit_search_delivery")
        self.horizontalLayout_Delivery.addWidget(self.lineEdit_search_delivery)
        self.search_btn_delivery = QtWidgets.QPushButton(self.Delivery)
        self.search_btn_delivery.setMinimumSize(QtCore.QSize(100, 75))
        self.search_btn_delivery.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_btn_delivery.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}"
        )
        self.search_btn_delivery.setObjectName("search_btn_delivery")
        self.horizontalLayout_Delivery.addWidget(self.search_btn_delivery)
        self.btn_otchet_Delivery = QtWidgets.QPushButton(self.Delivery)
        self.btn_otchet_Delivery.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_otchet_Delivery.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_otchet_Delivery.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_otchet_Delivery.setObjectName("btn_otchet_Delivery")
        self.horizontalLayout_Delivery.addWidget(self.btn_otchet_Delivery)
        self.verticalLayout.addLayout(self.horizontalLayout_Delivery)
        self.tabWidget_main.addTab(self.Delivery, "")
        self.venicle = QtWidgets.QWidget()
        self.venicle.setObjectName("venicle")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.venicle)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_venicle = QtWidgets.QTableWidget(self.venicle)
        self.tableWidget_venicle.setObjectName("tableWidget_venicle")
        self.tableWidget_venicle.setColumnCount(0)
        self.tableWidget_venicle.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidget_venicle)
        self.horizontalLayout_venicle = QtWidgets.QHBoxLayout()
        self.horizontalLayout_venicle.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_venicle.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_venicle.setSpacing(10)
        self.horizontalLayout_venicle.setObjectName("horizontalLayout_venicle")
        self.btn_add_venicle = QtWidgets.QPushButton(self.venicle)
        self.btn_add_venicle.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_venicle.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_venicle.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_add_venicle.setObjectName("btn_add_venicle")
        self.horizontalLayout_venicle.addWidget(self.btn_add_venicle)
        self.btn_edit_venicle = QtWidgets.QPushButton(self.venicle)
        self.btn_edit_venicle.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_venicle.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_venicle.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_edit_venicle.setObjectName("btn_edit_venicle")
        self.horizontalLayout_venicle.addWidget(self.btn_edit_venicle)
        self.btn_delete_venicle = QtWidgets.QPushButton(self.venicle)
        self.btn_delete_venicle.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_venicle.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_venicle.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_venicle.setObjectName("btn_delete_venicle")
        self.horizontalLayout_venicle.addWidget(self.btn_delete_venicle)
        self.lineEdit_search_venicle = QtWidgets.QLineEdit(self.venicle)
        self.lineEdit_search_venicle.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_search_venicle.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_search_venicle.setStyleSheet(
            "border: 3 solid rgb(0, 0, 0);\n"
            "border-radius: 10;\n"
            'font: 75 10pt "MS Shell Dlg 2";'
        )
        self.lineEdit_search_venicle.setObjectName("lineEdit_search_venicle")
        self.horizontalLayout_venicle.addWidget(self.lineEdit_search_venicle)
        self.search_btn_venicle = QtWidgets.QPushButton(self.venicle)
        self.search_btn_venicle.setMinimumSize(QtCore.QSize(0, 75))
        self.search_btn_venicle.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_btn_venicle.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}"
        )
        self.search_btn_venicle.setObjectName("search_btn_venicle")
        self.horizontalLayout_venicle.addWidget(self.search_btn_venicle)
        self.verticalLayout_7.addLayout(self.horizontalLayout_venicle)
        self.tabWidget_main.addTab(self.venicle, "")
        self.staff = QtWidgets.QWidget()
        self.staff.setObjectName("staff")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.staff)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidget_staff = QtWidgets.QTableWidget(self.staff)
        self.tableWidget_staff.setObjectName("tableWidget_staff")
        self.tableWidget_staff.setColumnCount(0)
        self.tableWidget_staff.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tableWidget_staff)
        self.horizontalLayout_staff = QtWidgets.QHBoxLayout()
        self.horizontalLayout_staff.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_staff.setContentsMargins(10, 10, 10, 5)
        self.horizontalLayout_staff.setSpacing(10)
        self.horizontalLayout_staff.setObjectName("horizontalLayout_staff")
        self.btn_add_staff = QtWidgets.QPushButton(self.staff)
        self.btn_add_staff.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_staff.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_staff.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_add_staff.setObjectName("btn_add_staff")
        self.horizontalLayout_staff.addWidget(self.btn_add_staff)
        self.btn_edit_staff = QtWidgets.QPushButton(self.staff)
        self.btn_edit_staff.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_staff.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_staff.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_edit_staff.setObjectName("btn_edit_staff")
        self.horizontalLayout_staff.addWidget(self.btn_edit_staff)
        self.btn_delete_staff = QtWidgets.QPushButton(self.staff)
        self.btn_delete_staff.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_staff.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_staff.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.btn_delete_staff.setObjectName("btn_delete_staff")
        self.horizontalLayout_staff.addWidget(self.btn_delete_staff)
        self.lineEdit_search_staff = QtWidgets.QLineEdit(self.staff)
        self.lineEdit_search_staff.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_search_staff.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_search_staff.setStyleSheet(
            "border: 3 solid rgb(0, 0, 0);\n"
            "border-radius: 10;\n"
            'font: 75 10pt "MS Shell Dlg 2";'
        )
        self.lineEdit_search_staff.setObjectName("lineEdit_search_staff")
        self.horizontalLayout_staff.addWidget(self.lineEdit_search_staff)
        self.search_btn_staff = QtWidgets.QPushButton(self.staff)
        self.search_btn_staff.setMinimumSize(QtCore.QSize(0, 75))
        self.search_btn_staff.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_btn_staff.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 10px;\n"
            "    background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}"
        )
        self.search_btn_staff.setObjectName("search_btn_staff")
        self.horizontalLayout_staff.addWidget(self.search_btn_staff)
        self.verticalLayout_8.addLayout(self.horizontalLayout_staff)
        self.tabWidget_main.addTab(self.staff, "")
        self.verticalLayout_2.addWidget(self.tabWidget_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tableWidget_venicle, self.tableWidget_orders)
        MainWindow.setTabOrder(self.tableWidget_orders, self.tableWidget_suppliers)
        MainWindow.setTabOrder(self.tableWidget_suppliers, self.tableWidget_staff)
        MainWindow.setTabOrder(self.tableWidget_staff, self.btn_delete_product)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Учет на складе"))
        self.btn_edit_product.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_product.setText(_translate("MainWindow", "Удалить запись"))
        self.search_btn_product.setText(_translate("MainWindow", "Поиск"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.products),
            _translate("MainWindow", "Продукция"),
        )
        self.btn_add_orders.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_order.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_order.setText(_translate("MainWindow", "Аннулировать заказ"))
        self.btn_delete_order_2.setText(_translate("MainWindow", "Заказ выполнен"))
        self.search_btn_order.setText(_translate("MainWindow", "Поиск"))
        self.btn_otchet_order.setText(_translate("MainWindow", "Сформировать отчет"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.orders), _translate("MainWindow", "Заказы")
        )
        self.btn_add_Clients.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_Clients.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_Clients.setText(_translate("MainWindow", "Удалить запись"))
        self.search_btn_clients.setText(_translate("MainWindow", "Поиск"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.Clients),
            _translate("MainWindow", "Клиенты"),
        )
        self.btn_add_suppliers.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_suppliers.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_suppliers.setText(_translate("MainWindow", "Удалить запись"))
        self.search_btn_suppliers.setText(_translate("MainWindow", "Поиск"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.suppliers),
            _translate("MainWindow", "Поставщики"),
        )
        self.btn_add_Delivery.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_Delivery.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_Delivery.setText(
            _translate("MainWindow", "Анулировать поставку")
        )
        self.btn_delete_Delivery_2.setText(
            _translate("MainWindow", "Поставка выполнена")
        )
        self.search_btn_delivery.setText(_translate("MainWindow", "Поиск"))
        self.btn_otchet_Delivery.setText(_translate("MainWindow", "Сформировать отчет"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.Delivery),
            _translate("MainWindow", "Поставки"),
        )
        self.btn_add_venicle.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_venicle.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_venicle.setText(_translate("MainWindow", "Удалить запись"))
        self.search_btn_venicle.setText(_translate("MainWindow", "Поиск"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.venicle),
            _translate("MainWindow", "Транспортные средства"),
        )
        self.btn_add_staff.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_staff.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_staff.setText(_translate("MainWindow", "Удалить запись"))
        self.search_btn_staff.setText(_translate("MainWindow", "Поиск"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.staff),
            _translate("MainWindow", "Сотрудники"),
        )
