# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1556, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "font: 75 14pt \"MS Shell Dlg 2\";\n"
            "font: 12pt \"MS Shell Dlg 2\";"
        )
        self.tabWidget_main.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_main.setDocumentMode(True)
        self.tabWidget_main.setTabsClosable(False)
        self.tabWidget_main.setMovable(False)
        self.tabWidget_main.setTabBarAutoHide(False)
        self.tabWidget_main.setObjectName("tabWidget_main")


        self.products = QtWidgets.QWidget()
        self.products.setObjectName("products")
        self.verticalLayout_product = QtWidgets.QVBoxLayout(self.products)
        self.verticalLayout_product.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.verticalLayout_product.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout_product.setSpacing(10)
        self.verticalLayout_product.setObjectName("verticalLayout_product")
        self.tableWidget_Product = QtWidgets.QTableWidget(self.products)
        self.tableWidget_Product.setObjectName("tableWidget_Product")
        self.tableWidget_Product.setColumnCount(0)
        self.tableWidget_Product.setRowCount(0)
        self.verticalLayout_product.addWidget(self.tableWidget_Product)
        self.horizontalLayout_product = QtWidgets.QHBoxLayout()
        self.horizontalLayout_product.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_product.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_product.setObjectName("horizontalLayout_product")
        self.btn_add_product = QtWidgets.QPushButton(self.products)
        self.btn_add_product.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_product.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_product.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_add_product.setObjectName("btn_add_product")
        self.horizontalLayout_product.addWidget(self.btn_add_product)
        self.btn_edit_product = QtWidgets.QPushButton(self.products)
        self.btn_edit_product.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_product.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_product.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_edit_product.setObjectName("btn_edit_product")
        self.horizontalLayout_product.addWidget(self.btn_edit_product)
        self.btn_delete_product = QtWidgets.QPushButton(self.products)
        self.btn_delete_product.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_product.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_product.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_delete_product.setObjectName("btn_delete_product")
        self.horizontalLayout_product.addWidget(self.btn_delete_product)
        self.verticalLayout_product.addLayout(self.horizontalLayout_product)
        self.tabWidget_main.addTab(self.products, "")
        self.orders = QtWidgets.QWidget()
        self.orders.setObjectName("orders")
        self.verticalLayout_order = QtWidgets.QVBoxLayout(self.orders)
        self.verticalLayout_order.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout_order.setSpacing(10)
        self.verticalLayout_order.setObjectName("verticalLayout_order")
        self.tableWidget_orders = QtWidgets.QTableWidget(self.orders)
        self.tableWidget_orders.setObjectName("tableWidget_orders")
        self.tableWidget_orders.setColumnCount(0)
        self.tableWidget_orders.setRowCount(0)
        self.verticalLayout_order.addWidget(self.tableWidget_orders)
        self.horizontalLayout_order = QtWidgets.QHBoxLayout()
        self.horizontalLayout_order.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_order.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_order.setObjectName("horizontalLayout_order")
        self.btn_add_orders = QtWidgets.QPushButton(self.orders)
        self.btn_add_orders.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_orders.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_orders.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_add_orders.setObjectName("btn_add_orders")
        self.horizontalLayout_order.addWidget(self.btn_add_orders)
        self.btn_edit_order = QtWidgets.QPushButton(self.orders)
        self.btn_edit_order.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_order.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_order.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_edit_order.setObjectName("btn_edit_order")
        self.horizontalLayout_order.addWidget(self.btn_edit_order)
        self.btn_delete_order = QtWidgets.QPushButton(self.orders)
        self.btn_delete_order.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_order.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_order.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_delete_order.setObjectName("btn_delete_order")
        self.horizontalLayout_order.addWidget(self.btn_delete_order)
        self.verticalLayout_order.addLayout(self.horizontalLayout_order)
        self.tabWidget_main.addTab(self.orders, "")
        self.Clients = QtWidgets.QWidget()
        self.Clients.setObjectName("Clients")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Clients)
        self.verticalLayout_3.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_Clients = QtWidgets.QTableWidget(self.Clients)
        self.tableWidget_Clients.setObjectName("tableWidget_Clients")
        self.tableWidget_Clients.setColumnCount(0)
        self.tableWidget_Clients.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_Clients)##############################################
        self.horizontalLayout_order_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_order_2.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_order_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_order_2.setObjectName("horizontalLayout_order_2")
        self.btn_add_Clients = QtWidgets.QPushButton(self.Clients)
        self.btn_add_Clients.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_Clients.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_Clients.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_add_Clients.setObjectName("btn_add_Clients")
        self.horizontalLayout_order_2.addWidget(self.btn_add_Clients)
        self.btn_edit_Clients = QtWidgets.QPushButton(self.Clients)
        self.btn_edit_Clients.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_Clients.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_Clients.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_edit_Clients.setObjectName("btn_edit_Clients")
        self.horizontalLayout_order_2.addWidget(self.btn_edit_Clients)
        self.btn_delete_Clients = QtWidgets.QPushButton(self.Clients)
        self.btn_delete_Clients.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_Clients.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_Clients.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_delete_Clients.setObjectName("btn_delete_Clients")
        self.horizontalLayout_order_2.addWidget(self.btn_delete_Clients)
        self.verticalLayout_3.addLayout(self.horizontalLayout_order_2)
        self.tabWidget_main.addTab(self.Clients, "")
        self.suppliers = QtWidgets.QWidget()
        self.suppliers.setObjectName("suppliers")
        self.verticalLayout_suppliers = QtWidgets.QVBoxLayout(self.suppliers)
        self.verticalLayout_suppliers.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout_suppliers.setSpacing(10)
        self.verticalLayout_suppliers.setObjectName("verticalLayout_suppliers")
        self.tableWidget_suppliers = QtWidgets.QTableWidget(self.suppliers)
        self.tableWidget_suppliers.setObjectName("tableWidget_suppliers")
        self.tableWidget_suppliers.setColumnCount(0)
        self.tableWidget_suppliers.setRowCount(0)
        self.verticalLayout_suppliers.addWidget(self.tableWidget_suppliers)
        self.horizontalLayout_suppliers = QtWidgets.QHBoxLayout()
        self.horizontalLayout_suppliers.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_suppliers.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_suppliers.setObjectName("horizontalLayout_suppliers")
        self.btn_add_suppliers = QtWidgets.QPushButton(self.suppliers)
        self.btn_add_suppliers.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_suppliers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_suppliers.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_add_suppliers.setObjectName("btn_add_suppliers")
        self.horizontalLayout_suppliers.addWidget(self.btn_add_suppliers)
        self.btn_edit_suppliers = QtWidgets.QPushButton(self.suppliers)
        self.btn_edit_suppliers.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_suppliers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_suppliers.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_edit_suppliers.setObjectName("btn_edit_suppliers")
        self.horizontalLayout_suppliers.addWidget(self.btn_edit_suppliers)
        self.btn_delete_suppliers = QtWidgets.QPushButton(self.suppliers)
        self.btn_delete_suppliers.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_suppliers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_suppliers.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_delete_suppliers.setObjectName("btn_delete_suppliers")
        self.horizontalLayout_suppliers.addWidget(self.btn_delete_suppliers)
        self.verticalLayout_suppliers.addLayout(self.horizontalLayout_suppliers)
        self.tabWidget_main.addTab(self.suppliers, "")
        self.Delivery = QtWidgets.QWidget()
        self.Delivery.setObjectName("Delivery")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Delivery)
        self.verticalLayout.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_Delivery = QtWidgets.QTableWidget(self.Delivery)
        self.tableWidget_Delivery.setObjectName("tableWidget_Delivery")
        self.tableWidget_Delivery.setColumnCount(0)
        self.tableWidget_Delivery.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_Delivery)
        self.horizontalLayout_Delivery = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Delivery.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_Delivery.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_Delivery.setObjectName("horizontalLayout_Delivery")
        self.btn_add_Delivery = QtWidgets.QPushButton(self.Delivery)
        self.btn_add_Delivery.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_Delivery.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_Delivery.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_add_Delivery.setObjectName("btn_add_Delivery")
        self.horizontalLayout_Delivery.addWidget(self.btn_add_Delivery)
        self.btn_edit_Delivery = QtWidgets.QPushButton(self.Delivery)
        self.btn_edit_Delivery.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_Delivery.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_Delivery.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_edit_Delivery.setObjectName("btn_edit_Delivery")
        self.horizontalLayout_Delivery.addWidget(self.btn_edit_Delivery)
        self.btn_delete_Delivery = QtWidgets.QPushButton(self.Delivery)
        self.btn_delete_Delivery.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_Delivery.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_Delivery.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_delete_Delivery.setObjectName("btn_delete_Delivery")
        self.horizontalLayout_Delivery.addWidget(self.btn_delete_Delivery)
        self.verticalLayout.addLayout(self.horizontalLayout_Delivery)
        self.tabWidget_main.addTab(self.Delivery, "")
        self.venicle = QtWidgets.QWidget()
        self.venicle.setObjectName("venicle")
        self.verticalLayout_venicle = QtWidgets.QVBoxLayout(self.venicle)
        self.verticalLayout_venicle.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout_venicle.setSpacing(10)
        self.verticalLayout_venicle.setObjectName("verticalLayout_venicle")
        self.tableWidget_venicle = QtWidgets.QTableWidget(self.venicle)
        self.tableWidget_venicle.setObjectName("tableWidget_venicle")
        self.tableWidget_venicle.setColumnCount(0)
        self.tableWidget_venicle.setRowCount(0)
        self.verticalLayout_venicle.addWidget(self.tableWidget_venicle)
        self.horizontalLayout_venicle = QtWidgets.QHBoxLayout()
        self.horizontalLayout_venicle.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_venicle.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_venicle.setObjectName("horizontalLayout_venicle")
        self.btn_add_venicle = QtWidgets.QPushButton(self.venicle)
        self.btn_add_venicle.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_venicle.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_venicle.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_add_venicle.setObjectName("btn_add_venicle")
        self.horizontalLayout_venicle.addWidget(self.btn_add_venicle)
        self.btn_edit_venicle = QtWidgets.QPushButton(self.venicle)
        self.btn_edit_venicle.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_venicle.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_venicle.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_edit_venicle.setObjectName("btn_edit_venicle")
        self.horizontalLayout_venicle.addWidget(self.btn_edit_venicle)
        self.btn_delete_venicle = QtWidgets.QPushButton(self.venicle)
        self.btn_delete_venicle.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_venicle.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_venicle.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_delete_venicle.setObjectName("btn_delete_venicle")
        self.horizontalLayout_venicle.addWidget(self.btn_delete_venicle)
        self.verticalLayout_venicle.addLayout(self.horizontalLayout_venicle)
        self.tabWidget_main.addTab(self.venicle, "")
        self.staff = QtWidgets.QWidget()
        self.staff.setObjectName("staff")
        self.verticalLayout_staff = QtWidgets.QVBoxLayout(self.staff)
        self.verticalLayout_staff.setContentsMargins(10, 5, 10, 10)
        self.verticalLayout_staff.setSpacing(10)
        self.verticalLayout_staff.setObjectName("verticalLayout_staff")
        self.tableWidget_staff = QtWidgets.QTableWidget(self.staff)
        self.tableWidget_staff.setObjectName("tableWidget_staff")
        self.tableWidget_staff.setColumnCount(0)
        self.tableWidget_staff.setRowCount(0)
        self.verticalLayout_staff.addWidget(self.tableWidget_staff)
        self.horizontalLayout_staff = QtWidgets.QHBoxLayout()
        self.horizontalLayout_staff.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_staff.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_staff.setObjectName("horizontalLayout_staff")
        self.btn_add_staff = QtWidgets.QPushButton(self.staff)
        self.btn_add_staff.setMinimumSize(QtCore.QSize(100, 75))
        self.btn_add_staff.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_add_staff.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_add_staff.setObjectName("btn_add_staff")
        self.horizontalLayout_staff.addWidget(self.btn_add_staff)
        self.btn_edit_staff = QtWidgets.QPushButton(self.staff)
        self.btn_edit_staff.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_edit_staff.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_edit_staff.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_edit_staff.setObjectName("btn_edit_staff")
        self.horizontalLayout_staff.addWidget(self.btn_edit_staff)
        self.btn_delete_staff = QtWidgets.QPushButton(self.staff)
        self.btn_delete_staff.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_delete_staff.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_delete_staff.setStyleSheet(
            """
                QPushButton {
                    border-radius: 10px;\n
                    background-color: #0E0188;\n
                    color: rgb(255, 255, 255);\n
                }
                QPushButton:hover {
                    background-color: #070049;
                }
            """
        )
        self.btn_delete_staff.setObjectName("btn_delete_staff")
        self.horizontalLayout_staff.addWidget(self.btn_delete_staff)
        self.verticalLayout_staff.addLayout(self.horizontalLayout_staff)
        self.tabWidget_main.addTab(self.staff, "")
        self.verticalLayout_2.addWidget(self.tabWidget_main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tableWidget_venicle, self.tableWidget_orders)
        MainWindow.setTabOrder(self.tableWidget_orders, self.tableWidget_suppliers)
        MainWindow.setTabOrder(self.tableWidget_suppliers, self.tableWidget_staff)
        MainWindow.setTabOrder(self.tableWidget_staff, self.btn_delete_product)
        MainWindow.setTabOrder(self.btn_delete_product, self.btn_edit_product)
        MainWindow.setTabOrder(self.btn_edit_product, self.btn_add_product)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Учет на складе"))
        self.btn_add_product.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_product.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_product.setText(_translate("MainWindow", "Удалить запись"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.products),
            _translate("MainWindow", "Продукция"),
        )
        self.btn_add_orders.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_order.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_order.setText(_translate("MainWindow", "Удалить запись"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.orders), _translate("MainWindow", "Заказы")
        )
        self.btn_add_Clients.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_Clients.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_Clients.setText(_translate("MainWindow", "Удалить запись"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.Clients),
            _translate("MainWindow", "Клиенты"),
        )
        self.btn_add_suppliers.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_suppliers.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_suppliers.setText(_translate("MainWindow", "Удалить запись"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.suppliers),
            _translate("MainWindow", "Поставщики"),
        )
        self.btn_add_Delivery.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_Delivery.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_Delivery.setText(_translate("MainWindow", "Удалить запись"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.Delivery),
            _translate("MainWindow", "Поставки"),
        )
        self.btn_add_venicle.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_venicle.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_venicle.setText(_translate("MainWindow", "Удалить запись"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.venicle),
            _translate("MainWindow", "Транспортные средства"),
        )
        self.btn_add_staff.setText(_translate("MainWindow", "Добавить запись"))
        self.btn_edit_staff.setText(_translate("MainWindow", "Изменить запись"))
        self.btn_delete_staff.setText(_translate("MainWindow", "Удалить запись"))
        self.tabWidget_main.setTabText(
            self.tabWidget_main.indexOf(self.staff),
            _translate("MainWindow", "Сотрудники"),
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
