# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppliers.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditForm(object):
    def setupUi(self, AddEditForm_suppliers):
        AddEditForm_suppliers.setObjectName("AddEditForm_suppliers")
        AddEditForm_suppliers.setFixedSize(500, 322)
        AddEditForm_suppliers.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(AddEditForm_suppliers)
        self.centralwidget.setObjectName("centralwidget")
        self.labelProduct1 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct1.setGeometry(QtCore.QRect(50, 20, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelProduct1.sizePolicy().hasHeightForWidth()
        )
        self.labelProduct1.setSizePolicy(sizePolicy)
        self.labelProduct1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelProduct1.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProduct1.setTextFormat(QtCore.Qt.AutoText)
        self.labelProduct1.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelProduct1.setWordWrap(False)
        self.labelProduct1.setObjectName("labelProduct1")
        self.labelProduct2 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct2.setGeometry(QtCore.QRect(50, 115, 381, 31))
        self.labelProduct2.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct2.setObjectName("labelProduct2")
        self.lineEdit_Namesuppliers = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Namesuppliers.setGeometry(QtCore.QRect(40, 60, 421, 41))
        self.lineEdit_Namesuppliers.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_Namesuppliers.setText("")
        self.lineEdit_Namesuppliers.setObjectName("lineEdit_Namesuppliers")
        self.lineEdit_ContactInfosuppliers = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ContactInfosuppliers.setGeometry(QtCore.QRect(40, 160, 421, 41))
        self.lineEdit_ContactInfosuppliers.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_ContactInfosuppliers.setObjectName("lineEdit_lineEdit_ContactInfosuppliers")
        self.OkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OkBtn.setGeometry(QtCore.QRect(50, 230, 130, 70))
        self.OkBtn.setStyleSheet(
            "QPushButton {\n"
            "     border-radius: 10px;\n"
            "     background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            '    font: 75 14pt "MS Shell Dlg 2";\n'
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.OkBtn.setObjectName("OkBtn")
        self.CancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CancelBtn.setGeometry(QtCore.QRect(320, 230, 130, 70))
        self.CancelBtn.setStyleSheet(
            " QPushButton {\n"
            "     border-radius: 10px;\n"
            "     background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            '    font: 75 14pt "MS Shell Dlg 2";\n'
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.CancelBtn.setObjectName("CancelBtn")
        AddEditForm_suppliers.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddEditForm_suppliers)
        QtCore.QMetaObject.connectSlotsByName(AddEditForm_suppliers)

    def retranslateUi(self, AddEditForm_suppliers):
        _translate = QtCore.QCoreApplication.translate
        AddEditForm_suppliers.setWindowTitle(
            _translate("AddEditForm_suppliers", "Добавить поставщика")
        )
        self.labelProduct1.setText(
            _translate("AddEditForm_suppliers", "Наименование организации")
        )
        self.labelProduct2.setText(
            _translate("AddEditForm_suppliers", "Номер телефона")
        )
        self.OkBtn.setText(_translate("AddEditForm_suppliers", "OK"))
        self.CancelBtn.setText(_translate("AddEditForm_suppliers", "Отмена"))