# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venicle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditForm(object):
    def setupUi(self, AddEditForm_venicle):
        AddEditForm_venicle.setObjectName("AddEditForm_venicle")
        AddEditForm_venicle.setFixedSize(961, 520)
        AddEditForm_venicle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(AddEditForm_venicle)
        self.centralwidget.setObjectName("centralwidget")
        self.labelProduct1 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct1.setGeometry(QtCore.QRect(50, 120, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelProduct1.sizePolicy().hasHeightForWidth()
        )
        self.labelProduct1.setSizePolicy(sizePolicy)
        self.labelProduct1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelProduct1.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProduct1.setTextFormat(QtCore.Qt.AutoText)
        self.labelProduct1.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelProduct1.setWordWrap(False)
        self.labelProduct1.setObjectName("labelProduct1")
        self.labelProduct2 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct2.setGeometry(QtCore.QRect(50, 215, 381, 31))
        self.labelProduct2.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct2.setObjectName("labelProduct2")
        self.labelProduct3 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct3.setGeometry(QtCore.QRect(510, 20, 401, 31))
        self.labelProduct3.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct3.setObjectName("labelProduct3")
        self.comboBox_venicle = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_venicle.setGeometry(QtCore.QRect(40, 60, 421, 41))
        self.comboBox_venicle.setStyleSheet(
            "QComboBox{    \n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}\n"
            "QComboBox::drop-down {\n"
            "    background-color: rgb(255, 255, 255);\n"
            "    border-radius: 8;\n"
            "    width: 30;\n"
            "}\n"
            "QComboBox::down-arrow {\n"
            "    width: 0px;\n"
            "    height: 0px;\n"
            "    border-left: 5px solid transparent;\n"
            "    border-right: 5px solid transparent;\n"
            "    border-top: 5px solid black; /* Цвет стрелки */\n"
            "}\n"
            "QComboBox QAbstractItemView {\n"
            "    margin-top: 2;\n"
            "    color: rgb(255, 255, 255);\n"
            "    background-color: #373e4e;\n"
            "    padding: 10;\n"
            "    selection-background-color: rgb(39, 44, 54);\n"
            "}"
        )
        self.comboBox_venicle.setObjectName("comboBox_venicle")
        self.lineEdit_mode_venicle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mode_venicle.setGeometry(QtCore.QRect(40, 160, 421, 41))
        self.lineEdit_mode_venicle.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_mode_venicle.setText("")
        self.lineEdit_mode_venicle.setObjectName("lineEdit_mode_venicle")
        self.lineEdit_registrationNumber_venicle = QtWidgets.QLineEdit(
            self.centralwidget
        )
        self.lineEdit_registrationNumber_venicle.setGeometry(
            QtCore.QRect(40, 260, 421, 41)
        )
        self.lineEdit_registrationNumber_venicle.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_registrationNumber_venicle.setObjectName(
            "lineEdit_registrationNumber_venicle"
        )
        self.lineEdit_capacity_venicle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_capacity_venicle.setGeometry(QtCore.QRect(40, 360, 421, 41))
        self.lineEdit_capacity_venicle.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_capacity_venicle.setObjectName("lineEdit_capacity_venicle")
        self.lineEdit_date_venicle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_date_venicle.setGeometry(QtCore.QRect(500, 60, 421, 41))
        self.lineEdit_date_venicle.setStyleSheet(
            "QLineEdit {\n"
            "    border: 3 solid rgb(0, 0, 0);\n"
            "    border-radius: 10;\n"
            "    padding: 5;\n"
            "    \n"
            '    font: 75 10pt "MS Shell Dlg 2";\n'
            "}"
        )
        self.lineEdit_date_venicle.setObjectName("lineEdit_date_venicle")
        self.calendarWidget_venicle = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget_venicle.setGeometry(QtCore.QRect(510, 140, 401, 241))
        self.calendarWidget_venicle.setStyleSheet(
            "background-color: rgb(67, 202, 202);\n"
            'font: 75 9pt "MS Shell Dlg 2";\n'
            "border-radius: 10;\n"
            "color: rgb(0, 0, 0);"
        )
        self.calendarWidget_venicle.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget_venicle.setObjectName("calendarWidget_venicle")
        self.OkBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OkBtn.setGeometry(QtCore.QRect(50, 430, 130, 70))
        self.OkBtn.setStyleSheet(
            "QPushButton {\n"
            "     border-radius: 10px;\n"
            "     background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            '    font: 75 14pt "MS Shell Dlg 2";\n'
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.OkBtn.setCheckable(False)
        self.OkBtn.setChecked(False)
        self.OkBtn.setObjectName("OkBtn")
        self.CancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CancelBtn.setGeometry(QtCore.QRect(780, 430, 130, 70))
        self.CancelBtn.setStyleSheet(
            " QPushButton {\n"
            "     border-radius: 10px;\n"
            "     background-color: #0E0188;\n"
            "    color: rgb(255, 255, 255);\n"
            '    font: 75 14pt "MS Shell Dlg 2";\n'
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #070049;\n"
            "}\n"
            ""
        )
        self.CancelBtn.setObjectName("CancelBtn")
        self.labelProduct2_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct2_2.setGeometry(QtCore.QRect(50, 315, 381, 31))
        self.labelProduct2_2.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct2_2.setObjectName("labelProduct2_2")
        self.labelProduct1_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelProduct1_2.setGeometry(QtCore.QRect(50, 20, 381, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelProduct1_2.sizePolicy().hasHeightForWidth()
        )
        self.labelProduct1_2.setSizePolicy(sizePolicy)
        self.labelProduct1_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelProduct1_2.setStyleSheet('font: 75 12pt "MS Shell Dlg 2";')
        self.labelProduct1_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelProduct1_2.setTextFormat(QtCore.Qt.AutoText)
        self.labelProduct1_2.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.labelProduct1_2.setWordWrap(False)
        self.labelProduct1_2.setObjectName("labelProduct1_2")
        AddEditForm_venicle.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddEditForm_venicle)
        QtCore.QMetaObject.connectSlotsByName(AddEditForm_venicle)

    def retranslateUi(self, AddEditForm_venicle):
        _translate = QtCore.QCoreApplication.translate
        AddEditForm_venicle.setWindowTitle(
            _translate("AddEditForm_venicle", "Добавить транспортное средство")
        )
        self.labelProduct1.setText(_translate("AddEditForm_venicle", "Модель машины"))
        self.labelProduct2.setText(_translate("AddEditForm_venicle", "Регистрационный номер"))
        self.labelProduct3.setText(_translate("AddEditForm_venicle", "Последнее тех. обслуживание транспорта"))
        self.OkBtn.setText(_translate("AddEditForm_venicle", "OK"))
        self.CancelBtn.setText(_translate("AddEditForm_venicle", "Отмена"))
        self.labelProduct2_2.setText(_translate("AddEditForm_venicle", "Грузоподъемность в тоннах"))
        self.labelProduct1_2.setText(_translate("AddEditForm_venicle", "Водитель"))

